import * as vscode from "vscode";
import { RulesService } from "../services/RulesService";
import { ConfigService } from "../services/ConfigService";

export async function generateCursorRules(): Promise<void> {
  const workspaceFolder = vscode.workspace.workspaceFolders?.[0];
  if (!workspaceFolder) {
    throw new Error("No workspace folder open");
  }

  const rulesService = new RulesService();
  const configService = new ConfigService();

  // Get current config
  const config = await configService.getConfig(workspaceFolder.uri);

  // Get all rules
  const rules = await rulesService.getRules(workspaceFolder.uri);

  // Filter enabled items
  const enabledRules = rules.filter((rule) =>
    config.enabledRules.includes(rule.id),
  );

  // Build the .cursorrules content
  const sections: string[] = [];

  // Header
  sections.push("# Generated by Cursor Rule Manager");
  sections.push(`# Last updated: ${new Date().toISOString()}`);
  sections.push("");

  // Add enabled rules
  if (enabledRules.length > 0) {
    sections.push(
      "# ═══════════════════════════════════════════════════════════════",
    );
    sections.push("# RULES");
    sections.push(
      "# ═══════════════════════════════════════════════════════════════",
    );
    sections.push("");

    for (const rule of enabledRules) {
      sections.push(`## ${rule.name}`);
      sections.push("");
      sections.push(rule.content.trim());
      sections.push("");
      sections.push("---");
      sections.push("");
    }
  }

  // If nothing is enabled, add a placeholder
  if (enabledRules.length === 0) {
    sections.push("# No rules are currently enabled.");
    sections.push("# Use the Rule Manager sidebar to enable rules.");
    sections.push("");
  }

  // Write the file
  const cursorRulesPath = vscode.Uri.joinPath(
    workspaceFolder.uri,
    ".cursorrules",
  );
  const content = sections.join("\n");

  await vscode.workspace.fs.writeFile(
    cursorRulesPath,
    Buffer.from(content, "utf8"),
  );
}
